name: 'Generate changelog'
description: 'Generate changelog'
inputs:
  github-token:  # id of input
    description: 'personal access token'
    required: true
runs:
  using: "composite"
  steps:
    using: 'node12'
    main: 'dist/index.js'